### ISSUE TITLE
filter by data

### ISSUE THREAD

**Issue by vsboost** [Buraddo23/CAN-Gateway#1]
Any way to filter by data instead of id or mask?  need to pass all traffic but only block one data frame 1AA#aabbccddeeff

**Comment by Buraddo23** [comment]
Hello, this project was a school assignment, I recommend you to use a more professional tool :) (like cangw)
The filter has been implemented only for id and mask. It has not occurred to me to implement other types of filters, but it is possible with some changes in the program. Maybe I will give a look on it one day.
